<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/*
|--------------------------------------------------------------------------
| ZIN-WORKS | Module 01 — Identity and Access (1 of 10)
|--------------------------------------------------------------------------
|
| Port of the PostgreSQL module-01 schema to MySQL 8. Adaptations made here,
| because MySQL has no direct equivalent:
|
|   CITEXT email      -> VARCHAR under the connection's utf8mb4_*_ci collation,
|                        which already compares case-insensitively. Same
|                        practical guarantee as citext for uniqueness/lookup.
|   gen_random_uuid() -> generated by the application. MySQL cannot use a
|                        function as a column DEFAULT for CHAR, so the model
|                        must supply it (Laravel's HasUuids trait).
|   Partial indexes   -> MySQL has no filtered indexes. `idx_users_status` is
|                        widened to (status, deleted_at) so the soft-delete
|                        predicate is still served by the index.
|   idx_users_login   -> dropped. In Postgres it was separate from the UNIQUE
|                        constraint because it was partial; in MySQL the
|                        UNIQUE index on `email` already serves those lookups,
|                        so a second index on the same column is dead weight.
|   touch_updated_at  -> replaced by ON UPDATE CURRENT_TIMESTAMP (section 10 of
|                        the source schema; no trigger needed).
|
| This table REPLACES the legacy `users` table from
| 0001_01_01_000000_create_users_table.php (bigint id, first_name/last_name,
| inline role enum). Because that migration always runs first, this one has to
| clear it. It will only do so when the table is empty — see up().
|
*/
return new class extends Migration
{
    public function up(): void
    {
        $this->dropLegacyUsersTable();

        Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary();

            $table->string('email')->nullable()->unique();
            $table->string('phone', 30)->nullable()->unique();
            $table->text('password_hash')->nullable();   // null for social-only accounts
            $table->enum('status', ['pending', 'active', 'suspended', 'banned', 'deleted'])
                ->default('pending');

            $table->string('display_name', 160)->nullable();
            $table->text('avatar_url')->nullable();
            $table->string('preferred_locale', 10)->default('en');   // 'en' or 'km'

            $table->timestamp('email_verified_at')->nullable();
            $table->timestamp('phone_verified_at')->nullable();
            $table->timestamp('last_login_at')->nullable();
            $table->smallInteger('failed_attempts')->default(0);
            $table->timestamp('locked_until')->nullable();

            $table->timestamp('created_at')->useCurrent();
            $table->timestamp('updated_at')->useCurrent()->useCurrentOnUpdate();
            $table->timestamp('deleted_at')->nullable();

            $table->index(['status', 'deleted_at'], 'idx_users_status');
        });

        // Must be reachable by at least one channel. A social-only account has no
        // password_hash by design; that a credential exists at all is enforced in
        // application code, since a CHECK cannot see user_identities.
        // Unquoted identifiers: backticks are MySQL-only, and this has to parse on
        // PostgreSQL too. Both engines accept these names bare.
        DB::statement('ALTER TABLE users ADD CONSTRAINT chk_contact CHECK (email IS NOT NULL OR phone IS NOT NULL)');
    }

    public function down(): void
    {
        Schema::dropIfExists('users');
    }

    /**
     * The legacy users table shares this name but not its shape: a BIGINT id
     * cannot carry a FK from the UUID tables in the rest of this module, so the
     * two cannot coexist. Dropping it with rows present would destroy accounts,
     * so refuse and let a human decide how the data should be carried across.
     */
    private function dropLegacyUsersTable(): void
    {
        if (! Schema::hasTable('users')) {
            return;
        }

        // Opt-in is required even when the table is empty. `migrate:fresh` drops and
        // recreates the legacy table moments before this runs, so an empty table
        // cannot be told apart from one whose accounts fresh discarded a second
        // earlier — which is exactly how this schema went live by accident once.
        // Read through config, not env(): env() returns null once the config
        // cache exists, which switched this opt-in off behind our backs and
        // made the migration refuse even with the value set in .env.
        if (! filter_var(config('module01.replace_users', false), FILTER_VALIDATE_BOOLEAN)) {
            $cachedConfig = file_exists(base_path('bootstrap/cache/config.php'));

            throw new RuntimeException(
                "Refusing to replace the legacy `users` table without an explicit opt-in.\n"
                . "Module 01 changes the primary key from BIGINT to UUID, so the two cannot coexist and\n"
                . "adopting it discards every existing account.\n\n"
                . "When you actually intend that, set MODULE01_REPLACE_USERS=true in .env and re-run.\n"
                . ($cachedConfig
                    ? "NOTE: bootstrap/cache/config.php exists, so .env is not being read at all.\n"
                    . "If you have already set the value, run `php artisan config:clear` and re-run.\n"
                    : '')
                . "Back up `users` first — the app's User model, auth, and the user screens all still\n"
                . "target the legacy columns and will need rewriting onto UUIDs and user_roles."
            );
        }

        $rows = DB::table('users')->count();

        if ($rows > 0) {
            throw new RuntimeException(
                "Refusing to replace the legacy `users` table: it still holds {$rows} row(s).\n"
                . "Back up and empty it first, or write a data-migration step that maps the old rows\n"
                . "(first_name/last_name -> display_name, role enum -> user_roles) onto the new shape."
            );
        }

        Schema::drop('users');
    }
};
