<?php

return [
    [
        'id' => 'retail-associates',
        'title' => 'Retail Associates',
        'company' => 'ABA Bank',
        'location' => 'Phnom Penh, Cambodia',
        'salary' => '$19.25 - $20.25 an hour',
        'short_salary' => '$19.25 - $20.25 / hour',
        'summary' => 'Help customers, support branch operations, and create a welcoming banking experience.',
        'type' => 'Full-time',
        'mode' => 'On-site',
        'experience' => '1+ Years',
        'department' => 'Retail Banking',
        'deadline' => '5 days left',
        'posted' => 'Posted 1 day ago',
        'posted_days' => 1,
        'applicants' => '48 applicants',
        'featured' => true,
        'highlighted' => false,
        'logo' => 'aba',
        'badges' => ['Full-time', 'On-site'],
        'tabs' => [
            'description' => [
                'title' => 'Support Customers With Confidence',
                'body' => 'ABA Bank is hiring service-minded retail associates to deliver a polished branch experience, guide customers through day-to-day banking needs, and help maintain a fast, organized front office.',
                'list_title' => 'What You Will Do',
                'list' => [
                    'Welcome customers and guide them to the right service desk',
                    'Process branch requests accurately and efficiently',
                    'Coordinate with branch managers on queue flow and escalations',
                    'Keep customer-facing materials current and compliant',
                ],
            ],
            'requirements' => [
                'title' => 'Preferred Qualifications',
                'body' => 'We are looking for someone dependable, friendly, and comfortable working in a customer-facing environment with clear service standards.',
                'list_title' => 'What Helps You Stand Out',
                'list' => [
                    'Previous front-desk, teller, or retail support experience',
                    'Strong communication in Khmer and English',
                    'Confidence handling customer questions under pressure',
                    'A detail-oriented, service-first mindset',
                ],
            ],
            'company' => [
                'title' => 'About ABA Bank',
                'body' => 'ABA Bank is one of Cambodia’s leading financial institutions, known for customer trust, accessible services, and strong digital banking adoption.',
                'list_title' => 'Why Join',
                'list' => [
                    'Structured onboarding and branch training',
                    'Clear growth paths into operations and service leadership',
                    'A high-volume environment that builds valuable customer skills',
                ],
            ],
        ],
        'detail_items' => [
            ['label' => 'Job type', 'value' => 'Full-time'],
            ['label' => 'Work mode', 'value' => 'On-site'],
            ['label' => 'Experience', 'value' => '1+ years'],
            ['label' => 'Department', 'value' => 'Retail Banking'],
        ],
        'quick_apply' => [
            'title' => 'Branch hiring',
            'text' => 'Applications are reviewed daily for immediate openings.',
        ],
    ],
    [
        'id' => 'software-engineer',
        'title' => 'Software Engineer',
        'company' => 'Tech Corp',
        'location' => 'Remote',
        'salary' => '$80,000 - $120,000 a year',
        'short_salary' => '$80k - $120k / year',
        'summary' => 'Build reliable digital products with a collaborative, remote-first engineering team.',
        'type' => 'Full-time',
        'mode' => 'Remote',
        'experience' => '3+ Years',
        'department' => 'Engineering',
        'deadline' => '10 days left',
        'posted' => 'Posted 3 days ago',
        'posted_days' => 3,
        'applicants' => '245 applicants',
        'featured' => true,
        'highlighted' => true,
        'logo' => 'tech',
        'badges' => ['Full-time', 'Remote'],
        'tabs' => [
            'description' => [
                'title' => 'Build Products That Matter',
                'body' => 'We are looking for a thoughtful Software Engineer to develop useful, reliable products. You will work remotely with a collaborative team and own meaningful work from idea to release.',
                'list_title' => 'What You Will Do',
                'list' => [
                    'Develop and maintain production web applications',
                    'Work with modern technologies and pragmatic patterns',
                    'Collaborate closely with product and design partners',
                    'Write clean, efficient, and well-documented code',
                ],
            ],
            'requirements' => [
                'title' => 'What We Are Looking For',
                'body' => 'This role fits engineers who enjoy shipping product in a collaborative remote environment and can take ownership of features from design through release.',
                'list_title' => 'Core Skills',
                'list' => [
                    '3+ years building production web applications',
                    'Strong JavaScript or PHP fundamentals',
                    'Experience with relational databases and APIs',
                    'Comfort working asynchronously with distributed teams',
                ],
            ],
            'company' => [
                'title' => 'About Tech Corp',
                'body' => 'Tech Corp builds digital products for scaling teams across Southeast Asia with a focus on developer experience, reliable systems, and fast iteration.',
                'list_title' => 'Why Engineers Like It Here',
                'list' => [
                    'Remote-first culture with flexible schedules',
                    'Clear ownership and meaningful product work',
                    'Supportive teammates with strong mentoring habits',
                ],
            ],
        ],
        'detail_items' => [
            ['label' => 'Job type', 'value' => 'Full-time'],
            ['label' => 'Work mode', 'value' => 'Remote'],
            ['label' => 'Experience', 'value' => '3+ years'],
            ['label' => 'Department', 'value' => 'Engineering'],
        ],
        'quick_apply' => [
            'title' => 'Quick apply',
            'text' => 'Apply today and expect an initial response within three days.',
        ],
    ],
    [
        'id' => 'ui-ux-designer',
        'title' => 'UI/UX Designer',
        'company' => 'Design Studio',
        'location' => 'Phnom Penh, Cambodia',
        'salary' => '$60,000 - $90,000 a year',
        'short_salary' => '$60k - $90k / year',
        'summary' => 'Shape intuitive product experiences for ambitious teams across Southeast Asia.',
        'type' => 'Full-time',
        'mode' => 'Hybrid',
        'experience' => '2+ Years',
        'department' => 'Product Design',
        'deadline' => '12 days left',
        'posted' => 'Posted 5 days ago',
        'posted_days' => 5,
        'applicants' => '94 applicants',
        'featured' => false,
        'highlighted' => false,
        'logo' => 'design',
        'badges' => ['Full-time', 'Hybrid'],
        'tabs' => [
            'description' => [
                'title' => 'Design Thoughtful Experiences',
                'body' => 'Design Studio is looking for a UI/UX Designer who can translate product ideas into clear user flows, polished interfaces, and a scalable design system.',
                'list_title' => 'In This Role You Will',
                'list' => [
                    'Create wireframes, prototypes, and production-ready UI',
                    'Partner closely with product managers and engineers',
                    'Contribute to a practical, scalable design system',
                    'Use research and feedback to improve usability',
                ],
            ],
            'requirements' => [
                'title' => 'What We Are Looking For',
                'body' => 'You should be comfortable owning design work end-to-end and presenting decisions clearly to both technical and non-technical teammates.',
                'list_title' => 'Preferred Experience',
                'list' => [
                    'A portfolio showing end-to-end product design work',
                    'Experience with Figma and prototyping workflows',
                    'Understanding of responsive design and accessibility',
                    'Ability to balance speed, polish, and product goals',
                ],
            ],
            'company' => [
                'title' => 'About Design Studio',
                'body' => 'Design Studio partners with startups and established brands to create digital experiences that feel modern, useful, and visually sharp.',
                'list_title' => 'What You Can Expect',
                'list' => [
                    'Cross-functional collaboration with product teams',
                    'A hybrid setup with focused creative studio time',
                    'Opportunities to shape brand and product direction',
                ],
            ],
        ],
        'detail_items' => [
            ['label' => 'Job type', 'value' => 'Full-time'],
            ['label' => 'Work mode', 'value' => 'Hybrid'],
            ['label' => 'Experience', 'value' => '2+ years'],
            ['label' => 'Department', 'value' => 'Product Design'],
        ],
        'quick_apply' => [
            'title' => 'Portfolio review',
            'text' => 'Share your best work and we will arrange a design conversation.',
        ],
    ],
];
